gdal2 depends on hdf4 fix
gdal2 wasn’t building because I had more than one formula named hdf4:

==> Upgrading osgeo/osgeo4mac/gdal2 --with-complete --with-opencl --with-armadillo --with-unsupported --with-l
Error: Formulae found in multiple taps:
       * osgeo/osgeo4mac/hdf4
       * brewsci/science/hdf4