Depend on our tap of libght
Without specifying the tap path, `brew install
osgeo/osgeo4mac/pointcloud` fails on my system with:

    Error: No available formula for libght (dependency of pointcloud)

We need to specify the full path to the formula for the install to
succeed.